# Site settings
author: Austin Burke
title: Mindful Monkeys
header-img: img/home-bg.png
email: aburk3@gmail.com
copyright_name: Austin Burke
description: > # this means to ignore newlines until "baseurl:"
  If you give a million monkeys each a keyboard...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aburk3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
